apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: serving-cert
  labels:
    role: webhook
  name: server
  namespace: gateway-admission-server
spec:
  selector:
   name: gateway-admission-server
   role: webhook
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
